In [1]:
import numpy as np
from sklearn import preprocessing

In [9]:
x = np.array([[1., -1., 2.],
            [2., 0., 0.],
             [0., 1., -1.]])

x.mean(axis = 0)

array([1.        , 0.        , 0.33333333])

In [10]:
x_scaled = preprocessing.scale(x)

In [16]:
x_scaled.mean(axis = 0)

array([0., 0., 0.])

In [17]:
x_scaled.std(axis = 0)

array([1., 1., 1.])

### When Scaling data training and testing data should be scale wirh same parameters otherwise Error can occur so we should combine the training and testing data before scaling but its impossible as in real world testing data comes after training data so we can't combine it so we should store the parameters of scaling of testing data

In [19]:
scaler = preprocessing.StandardScaler()
scaler.fit(x)

StandardScaler()

In [20]:
scaler.transform(x)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [21]:
x_test = [[1,1,0]]
scaler.transform(x_test)

array([[ 0.        ,  1.22474487, -0.26726124]])