### NumPy Library

In [2]:
import numpy as np
li_arr = [i for i in range(0,100)]
np_arr = np.arange(100)

print(li_arr)
print(np_arr)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [5]:
## size of one element in numpy array
print(np_arr.itemsize)

## size of whole array
print(np_arr.itemsize * np_arr.size)

4
400


In [12]:
import sys
a = 10
print(sys.getsizeof(a))
print(sys.getsizeof(a) * len(li_arr))

28
2800


In [14]:
import numpy as np
a = [1,2,3,4]
b = np.array(a)
print(b)
print(type(b))

[1 2 3 4]
<class 'numpy.ndarray'>


In [19]:
a = [1,2,3,'4',5.5]
b = np.array(a,dtype = int)
print(b)
print(type(b))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [20]:
b = np.full((3,3),8)
print(b)

[[8 8 8]
 [8 8 8]
 [8 8 8]]


In [24]:
c = np.empty((3,3))
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [31]:
list = [[1,2,3],[4,5,6],[7,8,9]]
np_array = np.array(list)
print(np_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
a = np.zeros(10,dtype = int)
a[4] = 5
print(a)

[0 0 0 0 5 0 0 0 0 0]


In [1]:
a = np.array([1, 2, 3, 4])
shape_a = a.shape

NameError: name 'np' is not defined

In [14]:
import numpy as np
a = np.linspace(3,10,3,dtype=int)
a

array([ 3,  6, 10])

In [22]:
b = np.ones((4,5,3),dtype=int)
b

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [31]:
a = np.random.rand(5,4) * 10
a

array([[6.41211134, 4.1082522 , 8.27317787, 2.94185846],
       [8.57308462, 9.62099519, 7.0668603 , 3.96371341],
       [2.42167165, 8.86028126, 5.68986229, 9.63123923],
       [6.48532981, 5.18920401, 8.78985988, 2.91045719],
       [5.17162344, 1.60401844, 5.29756035, 2.4701747 ]])

### randint

In [65]:
import numpy as np
a = np.random.randint(1,10 ,size = (4,5))
a

array([[3, 8, 3, 7, 2],
       [4, 6, 3, 3, 6],
       [9, 4, 5, 6, 5],
       [4, 3, 5, 2, 5]])

In [66]:
import numpy as np

# Generate a single random integer between 0 and 10 (exclusive)
random_int = np.random.randint(10)
print(random_int)

# Generate a single random integer between 5 and 10 (exclusive)
random_int_range = np.random.randint(5, 10)
print(random_int_range)

# Generate a 1D array of 5 random integers between 0 and 10 (exclusive)
array_1d = np.random.randint(0, 10, size=5)
print(array_1d)

# Generate a 2D array of shape (2, 3) with random integers between 1 and 100 (exclusive)
array_2d = np.random.randint(1, 100, size=(2, 3))
print(array_2d)

7
5
[7 2 3 4 1]
[[28  6 39]
 [48  8 51]]


In [67]:
np.random.randint(10,4)

ValueError: low >= high

In [78]:
import numpy as np
a = np.arange(9,50)
a

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
       26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49])

In [81]:
b = np.eye(5,6, dtype = int)
b

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0]])

In [87]:
c = np.linspace(0,5,10, dtype = float)
d = []
for x in c:
    d.append(round(x,2))

d

[0.0, 0.56, 1.11, 1.67, 2.22, 2.78, 3.33, 3.89, 4.44, 5.0]

In [89]:
li = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]]
import numpy as np
np_array = np.array(li)
print(np_array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [93]:
print(np_array[2,:3])
print(np_array[1:4,3])
print(np_array[2:4,:5])
print(np_array[1:3,1:3])

[11 12 13]
[ 9 14 19]
[[11 12 13 14 15]
 [16 17 18 19 20]]
[[ 7  8]
 [12 13]]


In [95]:
import numpy as np

li = [1,2,3,4,5]
a = np.random.randint(1,20,5)
b = np.random.randint(1,20,5)

print(li)
print(a)
print(b)

[1, 2, 3, 4, 5]
[ 2  7 18 13 11]
[ 4  3  4  8 17]


In [97]:
li = [i + 1 for i in li]
print(li)

a = a + 1
print(a)

[3, 4, 5, 6, 7]
[ 3  8 19 14 12]


In [104]:
import numpy as np
li = [1,2,0,0,4,0]

arr = np.array(li)
print(arr[arr != 0])
ind = np.where(arr != 0)
print(ind)

[1 2 4]
(array([0, 1, 4], dtype=int64),)
[array([0, 1, 4], dtype=int64)]


In [109]:
import numpy as np
li = [1,3,5,7,9,11,13,15,17,19]
arr = np.array(li)
mul = arr[arr % 3 == 0]
mul
ind = np.where(arr % 3 == 0)
print(ind)

(array([1, 4, 7], dtype=int64),)


In [113]:
import numpy as np
arr = np.arange(1,11)
arr[arr & 1 == 1] = -1
print(arr)

[-1  2 -1  4 -1  6 -1  8 -1 10]


In [122]:
import numpy as np
li = [11,2,13,4,15,6,27,8,19]
arr = np.array(li)
a =  arr.argmax()
arr[a] = 0
arr

array([11,  2, 13,  4, 15,  6,  0,  8, 19])

In [126]:
import numpy as np

arr = np.arange(1, 11)  # Create array from 1 to 10
mask = (arr >= 3) & (arr <= 8)  # Create boolean mask for values between 3 and 8
arr[mask] = ~arr[mask]  # Negate values between 3 and 8

print(arr)


[ 1  2 -4 -5 -6 -7 -8 -9  9 10]


In [127]:
import numpy as np

# Heights array (in centimeters)
heights = np.random.randint(140, 200, size=20)

# Ages array (in years)
ages = np.random.randint(18, 80, size=20)

print("Heights:", heights)
print("Ages:", ages)

Heights: [181 152 179 186 161 184 190 153 172 192 184 144 188 174 171 183 191 176
 197 197]
Ages: [67 40 19 22 67 53 26 22 48 57 26 64 48 32 64 30 45 77 23 39]


In [129]:
ind = np.where(heights > 155)
print(ind)

(array([ 0,  2,  3,  4,  5,  6,  8,  9, 10, 12, 13, 14, 15, 16, 17, 18, 19],
      dtype=int64),)


In [130]:
print(ages[ind])

[67 19 22 67 53 26 48 57 26 48 32 64 30 45 77 23 39]


In [1]:
import numpy as np
a = np.random.randint(1,30,(5,6))
a

array([[13, 16,  1, 11,  9, 15],
       [ 7, 13, 20, 29,  2, 12],
       [26, 18, 25,  6, 29, 21],
       [27, 27,  4,  3, 12, 28],
       [21,  4, 15, 19, 22, 23]])

In [6]:
arr = a > 20
print(arr)

b = a[arr]
print(b)

[[False False False False False False]
 [False False False  True False False]
 [ True False  True False  True  True]
 [ True  True False False False  True]
 [ True False False False  True  True]]
[29 26 25 29 21 27 27 28 21 22 23]


In [7]:
a[arr] = 100

In [8]:
a

array([[ 13,  16,   1,  11,   9,  15],
       [  7,  13,  20, 100,   2,  12],
       [100,  18, 100,   6, 100, 100],
       [100, 100,   4,   3,  12, 100],
       [100,   4,  15,  19, 100, 100]])

In [9]:
bool_arr = a[:,3] == 100
print(bool_arr)

[False  True False False False]


In [10]:
print(a[bool_arr])

[[  7  13  20 100   2  12]]


In [11]:
a[bool_arr,3]=99
print(a)

[[ 13  16   1  11   9  15]
 [  7  13  20  99   2  12]
 [100  18 100   6 100 100]
 [100 100   4   3  12 100]
 [100   4  15  19 100 100]]


In [12]:
import numpy as np

# Sample 2D numpy array
arr = np.array([[3, 2, 5, 4, 1],
                [9, 8, 7, 6, 5],
                [1, 0, 3, 2, 6],
                [4, 5, 2, 7, 8]])

# Get the indices that would sort the array by the second column (index 1)
sorted_indices = arr[:, 1].argsort()

# Use the sorted indices to rearrange the rows of the array
sorted_arr = arr[sorted_indices]

print("Sorted array by the 2nd column in ascending order:")
print(sorted_arr)


Sorted array by the 2nd column in ascending order:
[[1 0 3 2 6]
 [3 2 5 4 1]
 [4 5 2 7 8]
 [9 8 7 6 5]]


In [14]:
import numpy as np
a = np.random.randint(1,30,(5,6))
a

array([[27,  4,  5, 28, 10, 10],
       [10,  6, 26, 17, 18, 23],
       [ 2, 14, 20, 19, 26, 19],
       [24, 19, 19, 16, 11,  1],
       [28,  7,  8,  1, 25, 14]])

In [19]:
sorted_indices = a[:,:].argsort()
sorted_indices

array([[1, 2, 4, 5, 0, 3],
       [1, 0, 3, 4, 5, 2],
       [0, 1, 3, 5, 2, 4],
       [5, 4, 3, 1, 2, 0],
       [3, 1, 2, 5, 4, 0]], dtype=int64)

In [16]:
sorted_arr = a[sorted_indices]
print(sorted_arr)

[[27  4  5 28 10 10]
 [10  6 26 17 18 23]
 [28  7  8  1 25 14]
 [ 2 14 20 19 26 19]
 [24 19 19 16 11  1]]


### Broadcasting

In [20]:
import numpy as np
x = np.random.randint(1,10,(3,3))
y = np.random.randint(1,10,3)
print(x)
print(y)

[[9 4 5]
 [1 1 6]
 [9 4 4]]
[7 4 7]


In [21]:
print(x - y)

[[ 2  0 -2]
 [-6 -3 -1]
 [ 2  0 -3]]


### Practice

In [5]:
import numpy as np
a = np.random.randint(1,10,10)
a

array([4, 3, 4, 7, 6, 5, 6, 7, 3, 6])

In [6]:
bool_arr = a > 4
bool_arr

array([False, False, False,  True,  True,  True,  True,  True, False,
        True])

In [8]:
new_arr = a[bool_arr]
new_arr

array([7, 6, 5, 6, 7, 6])

In [17]:
# a = [1,2,3,4,5]
# a[:3] = 19
# a

# a = np.random.randint(1,10,10)
# a[:3] = 19
# a

In [23]:
import numpy as np
a = np.random.randint(1,10,10)
print(a)
a[a > 3] = 19
print(a)

[6 4 2 1 9 9 6 7 7 4]
[19 19  2  1 19 19 19 19 19 19]


In [26]:
print(a[a == 19])

[19 19 19 19 19 19 19 19]


In [27]:
print(np.where(a == 19))

(array([0, 1, 4, 5, 6, 7, 8, 9], dtype=int64),)


In [30]:
import numpy as np

# Create a random numpy array
a = np.random.randint(1, 10, 10)
print(a)

# Create a boolean mask for elements between 3 and 8
mask = (a > 3) & (a < 8)
print(mask)

# # Negate the elements identified by the mask
a[mask] = -a[mask]

print(a)

[6 2 1 8 9 6 5 2 3 5]
[ True False False False False  True  True False False  True]
[-6  2  1  8  9 -6 -5  2  3 -5]


In [36]:
import numpy as np

# Heights in centimeters
heights = np.array([150, 165, 180, 155, 175, 168, 172, 163, 178, 185])

# Ages in years
ages = np.array([25, 30, 35, 40, 45, 28, 33, 38, 43, 50])

print("Heights:", heights)
print("Ages:", ages)

Heights: [150 165 180 155 175 168 172 163 178 185]
Ages: [25 30 35 40 45 28 33 38 43 50]


In [37]:
ind = heights > 155
print(ind)
print(ages[ind])

[False  True  True False  True  True  True  True  True  True]
[30 35 45 28 33 38 43 50]


In [39]:
import numpy as np
a = np.random.randint(1,30,(5,6))
a

array([[ 1, 21,  8, 23, 26, 20],
       [14, 26, 24, 14, 27, 28],
       [ 9,  3, 15, 26, 19,  9],
       [12, 20, 23,  4, 11,  5],
       [18,  4, 11, 26, 18,  7]])

In [41]:
bool_arr = a > 20
print(bool_arr)

[[False  True False  True  True False]
 [False  True  True False  True  True]
 [False False False  True False False]
 [False False  True False False False]
 [False False False  True False False]]


In [42]:
new_arr = a[bool_arr]
print(new_arr)

[21 23 26 26 24 27 28 26 23 26]


In [44]:
a[bool_arr] = 100
print(a)

[[  1 100   8 100 100  20]
 [ 14 100 100  14 100 100]
 [  9   3  15 100  19   9]
 [ 12  20 100   4  11   5]
 [ 18   4  11 100  18   7]]


In [45]:
cool_arr = a[:3] == 100
cool_arr

array([[False,  True, False,  True,  True, False],
       [False,  True,  True, False,  True,  True],
       [False, False, False,  True, False, False]])

In [46]:
import numpy as np
a = np.random.randint(1,30,(5,6))
a

array([[26,  4, 27, 25,  1, 10],
       [12,  9, 21, 19,  5, 28],
       [27, 13,  5, 15, 11, 20],
       [ 6,  8, 26, 10,  9, 27],
       [15, 23, 17, 12,  9, 26]])

In [51]:
sorted_indices = a[:,1].argsort()
print(sorted_indices)

[0 3 1 2 4]


In [52]:
sorted_Arr = a[sorted_indices]
print(sorted_Arr)

[[26  4 27 25  1 10]
 [ 6  8 26 10  9 27]
 [12  9 21 19  5 28]
 [27 13  5 15 11 20]
 [15 23 17 12  9 26]]


### CSV

In [94]:
import numpy as np
import csv

with open('Dataset/year2017.csv') as file_obj:
    file_data = csv.DictReader(file_obj,skipinitialspace=True)
    killed = []
    wounded = []
    country = []
    for row in (file_data):
        killed.append(row['Killed'])
        wounded.append(row['Wounded'])
        country.append(row['Country'])
    np_killed = np.array(killed)
    np_wounded = np.array(wounded)
    print(np_killed)
    print(np_wounded)
    np_killed[np_killed == ''] = '0.0'
    np_wounded[np_wounded == ''] = '0.0'
    np_killed = np.array(np_killed,dtype=float)
    np_wounded = np.array(np_wounded,dtype=float)
    killed_wounded = np_killed + np_wounded
    print(killed+wounded)
    np_country = np.array(country)
    bool_ind = np_country == 'India'
    ans = killed_wounded[bool_ind]
    print(sum(killed_wounded))
    print(sum(ans))

['0.0' '2.0' '7.0' ... '0.0' '0.0' '0.0']
['0.0' '0.0' '0.0' ... '0.0' '0.0' '0.0']
['0.0', '2.0', '7.0', '7.0', '39.0', '4.0', '1.0', '0.0', '0.0', '0.0', '3.0', '0.0', '3.0', '1.0', '1.0', '0.0', '', '4.0', '', '0.0', '8.0', '1.0', '9.0', '0.0', '0.0', '1.0', '0.0', '0.0', '0.0', '0.0', '0.0', '6.0', '5.0', '0.0', '0.0', '1.0', '0.0', '10.0', '2.0', '36.0', '0.0', '2.0', '1.0', '0.0', '1.0', '4.0', '9.0', '3.0', '6.0', '5.0', '', '1.0', '1.0', '6.0', '1.0', '1.0', '0.0', '0.0', '1.0', '0.0', '3.0', '0.0', '3.0', '2.0', '1.0', '1.0', '0.0', '0.0', '2.0', '1.0', '1.0', '1.0', '2.0', '1.0', '0.0', '2.0', '', '2.0', '75.0', '93.0', '11.0', '0.0', '1.0', '0.0', '0.0', '0.0', '0.0', '1.0', '', '10.0', '1.0', '1.0', '0.0', '6.0', '0.0', '0.0', '0.0', '2.0', '7.0', '1.0', '4.0', '1.0', '0.0', '0.0', '', '0.0', '0.0', '1.0', '1.0', '2.0', '0.0', '1.0', '3.0', '3.0', '1.0', '1.0', '0.0', '0.0', '2.0', '0.0', '0.0', '0.0', '', '', '', '2.0', '3.0', '6.0', '1.0', '8.0', '0.0', '5.0', '0.0', '1.0

### QUESTIONS

In [ ]:
import csv 
import numpy as np

with open('Dataset/terrorismData.csv', encoding='utf-8') as file_obj:
    file_data = csv.reader(file_obj)
    country = []
    killed= []
    for row in (file_data):
        # country.append(row['Country'])
        # killed.append(row['Killed'])
        print(row)